In [11]:
#NumPy - It stands for numerical python 
#developed in 2005 by Travis Oliphant
#before 2005 there were special mathematical tools(similar to Tora, Linga)

In [5]:
import numpy as np 

In [3]:
np.__version__

'2.1.3'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [7]:
lis = [1,2,3, "Abhi", True , 1+2j] # list stores heterogenous data
type(lis)

list

In [8]:
#NumPy stores the data in numpy array
#Array - is a data structure used to store data of same datatype >> homogenous

In [10]:
#why NumPy?? already we have list, C is one of the fastest programming language after C++
#NumPy is built using C>> computation in NumPy is very fast 
# due to array >> since it stores only homogenous data , NumPy array is faster
#Since it stores homogenous data >> it has continuous memory location 

In [20]:
l = [1,2,3,4,5] # NumPy arrray is homogenous >> all element can be integer, float, string doesnt matter

In [16]:
arr = np.array(l)

In [19]:
type(arr)
#numpy.ndarray >> nd means N dimensional array


numpy.ndarray

In [22]:
l = [1,2,3,4,5 , "array"] 
np.array(l)

array(['1', '2', '3', '4', '5', 'array'], dtype='<U21')

In [23]:
#array stores homogenous data if you store a string with integers it will convert everything to string

In [25]:
l = [1,2,3,4,5 , 2.5]
np.array(l) # now it becomes float

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [26]:
type(arr)

numpy.ndarray

In [27]:
arr

array([1, 2, 3, 4, 5])

In [30]:
arr.ndim # it gives dimesion of the array # arr has only rows

1

In [31]:
#defining 2 dimesional array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [33]:
arr1.ndim

2

In [35]:
mat = np.matrix([1,2,3,4]) # matrix > is a specialised 2 dimension

In [36]:
type(mat)

numpy.matrix

In [37]:
mat.ndim

2

In [38]:
mat

matrix([[1, 2, 3, 4]])

In [40]:
#To understand see the dimension , see the opening and closing square bracket

In [ ]:
np.matrix([[[1,2],[3,4],[5,6]]]) #np.matrix([[[1,2],[3,4],[5,6]]]) gives error

In [42]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])

In [43]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [44]:
arr3.ndim

3

In [46]:
#more to convert array
l = [1,2,3]
np.asarray(l) # initial function to convert to an array, np.array came after this

array([1, 2, 3])

In [48]:
np.asanyarray([1,2,3])#asanyarray will convert the imput to an array but if something is already an arrray it will just pass it

array([1, 2, 3])

In [49]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [50]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [51]:
#converting a tuple into array
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [52]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
#accessing the elements of the array
arr

array([1, 2, 3, 4, 5])

In [55]:
arr[0]

np.int64(1)

In [56]:
#array is mutable
arr[0]= 100

In [57]:
arr

array([100,   2,   3,   4,   5])

In [58]:
#Concept of deep copy and shallow copy
# a and arr will point to same memory location and if there is change in a or arr it will reflect on both


In [64]:
a = arr #shallow copy>> change in one array will lead to change in another 

In [61]:
a

array([100,   2,   3,   4,   5])

In [62]:
arr

array([100,   2,   3,   4,   5])

In [68]:
a[0] = 5000 # it changes 1st position for both

In [66]:
a

array([5000,    2,    3,    4,    5])

In [67]:
arr

array([5000,    2,    3,    4,    5])

In [78]:
#Deep Copy # change in one copy will not reflect in another
b = arr.copy()

In [71]:
b

array([5000,    2,    3,    4,    5])

In [73]:
b[0] = 11000

In [77]:
b # it changes 

array([11000,     2,     3,     4,     5])

In [76]:
arr#it doesnt 

array([5000,    2,    3,    4,    5])

In [79]:
#To create an array>> np.array , np.asarray, np.asanyarray

In [80]:
#multiple approach to generate any array

In [101]:
np.fromfunction(lambda i , j : i==j , (3,3)) #construct an array by executing a function over each coordination

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [99]:
 np.fromfunction(lambda x,y :np.where(x < 2, x, 0), (2,2))

array([[0., 0.],
       [1., 1.]])

In [98]:
arr1.ndim

2

In [102]:
arr2 = np.fromfunction(lambda i , j : i==j , (3,3))

In [103]:
arr2.ndim

2

In [106]:
arr2.shape # shape of array

(3, 3)

In [108]:
arr2.size# number of elements in array

9

In [110]:
#True is stored as 1 and false is stored as 0 
np.fromfunction(lambda i,j :i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [111]:
arr4 = np.fromfunction(lambda i,j :i*j, (3,3))

In [112]:
arr4.ndim

2

In [113]:

arr4.shape

(3, 3)

In [114]:
arr4.size

9

In [115]:
for i in range(5):
    print(i)

0
1
2
3
4


In [116]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [1]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [2]:
iterator = (i for i in range(5))

In [3]:
iterator

<generator object <genexpr> at 0x000002D001EC1480>

In [6]:
np.fromiter(iterator, int)

array([0, 1, 2, 3, 4])

In [7]:
np.fromstring(' 22 23 24 ', sep = " ")

array([22., 23., 24.])

In [9]:
np.fromstring(' 22 23 24 ', sep = " " , dtype = int) # by default it is float

array([22, 23, 24])

In [10]:
#for string you have to use split
string = "Abhi , Khush , Kartik"
string.split(",")

['Abhi ', ' Khush ', ' Kartik']

In [12]:
np.array(string.split(","))

array(['Abhi ', ' Khush ', ' Kartik'], dtype='<U7')

In [13]:
range(10)

range(0, 10)

In [16]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
#other method to generate a sequence of number
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [19]:
np.linspace(1,5,10) # give me 10 numbers between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])