In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [5]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 1, 2]], dtype=int32)

In [6]:
arr1.flatten()#Return a copy of the array collapsed into one dimension.

array([1, 2, 2, 1, 2, 2, 1, 2, 2], dtype=int32)

In [7]:
#expand dimension
arr = np.array([1,2,3,4])

In [8]:
arr.ndim

1

In [10]:
np.expand_dims(arr, axis=0) # increase the dimesion by 1 in the provided axis , 0 means x axis & 1 means y axis

array([[1, 2, 3, 4]])

In [11]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr, axis=1).ndim

2

In [13]:
arr = np.zeros((3,4))

In [14]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr, axis = 0).ndim

3

In [17]:
np.expand_dims(arr, axis =1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [18]:
np.expand_dims(arr, axis =1).ndim

3

In [19]:
a = np.array([[1],[2],[3]])

In [20]:
a

array([[1],
       [2],
       [3]])

In [21]:
a.ndim

2

In [22]:
#squeezing the dimension
np.squeeze(a) #Remove axes of length one from `a`

array([1, 2, 3])

In [23]:
a

array([[1],
       [2],
       [3]])

In [24]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [25]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [26]:
np.repeat(arr1,2)

array([1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2], dtype=int32)

In [27]:
np.repeat(arr1,2 , axis=0)

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [29]:
np.repeat(arr2, 3, axis=0)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [30]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]], dtype=int32)

In [31]:
a

array([[1],
       [2],
       [3]])

In [32]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [33]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [35]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [36]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [39]:
np.roll(c,-2, axis = 0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [40]:
np.roll(c,-2, axis = 1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [42]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 1, 2]], dtype=int32)

In [43]:
arr1 + arr2

array([[3, 4, 4],
       [2, 3, 3],
       [3, 3, 4]], dtype=int32)

In [44]:
arr1 - arr2

array([[-1,  0,  0],
       [ 0,  1,  1],
       [-1,  1,  0]], dtype=int32)

In [45]:
arr1 * arr2

array([[2, 4, 4],
       [1, 2, 2],
       [2, 2, 4]], dtype=int32)

In [46]:
arr1>arr2

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [47]:
#Bitwise negation with arrays
~arr1

array([[-2, -3, -3],
       [-2, -3, -3],
       [-2, -3, -3]], dtype=int32)

In [48]:
#operations on NumPy string array

d = np.array(["Abhi" , "jeet"])

In [49]:
d

array(['Abhi', 'jeet'], dtype='<U4')

In [50]:
np.char.upper(d)

array(['ABHI', 'JEET'], dtype='<U4')

In [51]:
np.char.lower(d)

array(['abhi', 'jeet'], dtype='<U4')

In [52]:
np.char.capitalize(d)

array(['Abhi', 'Jeet'], dtype='<U4')

In [53]:
#Mathematical function

In [54]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [55]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743]])

In [56]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.41614684],
       [ 0.54030231, -0.41614684, -0.41614684],
       [ 0.54030231, -0.41614684, -0.41614684]])

In [57]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986]])

In [58]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103]])

In [59]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [61]:
np.power(arr1 , 3)

array([[1, 8, 8],
       [1, 8, 8],
       [1, 8, 8]], dtype=int32)

In [62]:
np.max(arr1)

np.int32(2)

In [63]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [64]:
np.mean(arr1)

np.float64(1.6666666666666667)

In [65]:
np.min(arr1)

np.int32(1)

In [66]:
np.std(arr1)

np.float64(0.4714045207910317)

In [67]:
np.var(arr1)

np.float64(0.2222222222222222)

In [68]:
arr1 - arr2

array([[-1,  0,  0],
       [ 0,  1,  1],
       [-1,  1,  0]], dtype=int32)

In [69]:
np.subtract(arr1,arr2)

array([[-1,  0,  0],
       [ 0,  1,  1],
       [-1,  1,  0]], dtype=int32)

In [70]:
arr1 * arr2

array([[2, 4, 4],
       [1, 2, 2],
       [2, 2, 4]], dtype=int32)

In [72]:
np.multiply(arr1,arr2)

array([[2, 4, 4],
       [1, 2, 2],
       [2, 2, 4]], dtype=int32)

In [73]:
np.mod(arr1,arr2) # return element wise remainder

array([[1, 0, 0],
       [0, 0, 0],
       [1, 0, 0]], dtype=int32)

In [74]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [75]:
#sorting and searching in numpy array
e = np.array([5,6,1,2])

In [76]:
e

array([5, 6, 1, 2])

In [77]:
np.sort(e)

array([1, 2, 5, 6])

In [78]:
f = np.array([5,199,200,3,6,7,8])
f

array([  5, 199, 200,   3,   6,   7,   8])

In [79]:
np.sort(f)

array([  3,   5,   6,   7,   8, 199, 200])

In [80]:
np.searchsorted(f , 170)  #Find indices where elements should be inserted to maintain order.

np.int64(7)

In [82]:
f = np.array([5,199,200,3,6,7,8,0,0,0,0])
f

array([  5, 199, 200,   3,   6,   7,   8,   0,   0,   0,   0])

In [84]:
np.count_nonzero(f)

7

In [85]:
np.sort(f)

array([  0,   0,   0,   0,   3,   5,   6,   7,   8, 199, 200])

In [87]:
f[f>0]

array([  5, 199, 200,   3,   6,   7,   8])

In [89]:
np.where(f>0) # same as above condition

(array([0, 1, 2, 3, 4, 5, 6]),)

In [91]:
np.extract(f>0 , f) # same as above condition

array([  5, 199, 200,   3,   6,   7,   8])

In [92]:
f

array([  5, 199, 200,   3,   6,   7,   8,   0,   0,   0,   0])

In [93]:
f.byteswap()#Swap the bytes of the array elements

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         216172782113783808,   432345564227567616,   504403158265495552,
         576460752303423488,                    0,                    0,
                          0,                    0])

In [94]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [98]:
nm.ones((3,4) , dtype = int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [99]:
#numpy linear algebra(optional)

In [100]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [101]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 1, 2]], dtype=int32)

In [102]:
arr1 @ arr2

array([[8, 6, 8],
       [8, 6, 8],
       [8, 6, 8]], dtype=int32)

In [103]:
np.linalg.det(arr1)

np.float64(0.0)

In [104]:
np.linalg.det(arr2)

np.float64(0.0)

In [105]:
#in matrix you cannot divide by another matrix >> u have inverse

In [ ]:
np.linalg.inv(arr2)

In [111]:
#SOLVING SIMULTANEOUS 
a = np.array([[7, 5.3, -3],[3,-5,2],[5,3,-7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [112]:
b = np.array([16,8,0])

In [113]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])