In [1]:
import numpy as np

In [2]:
#all elements as zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
a = np.zeros(5)

In [5]:
a.ndim

1

In [6]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [8]:
#2 dimn zeros
np.zeros((3,4) , dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
b = np.zeros((3,4) , dtype = int)

In [11]:
b.ndim

2

In [14]:
# for ones in array
a = np.ones(5, dtype = int)

In [15]:
a

array([1, 1, 1, 1, 1])

In [16]:
np.ones((3,3) , dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [19]:
arr = np.zeros((3,4))

In [20]:
arr.ndim

2

In [29]:
#3-dim array
arr = np.zeros((1,3,4))

In [30]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
arr.ndim

3

In [25]:
arr.size

12

In [26]:
arr.shape

(1, 3, 4)

In [35]:
arr = np.zeros((3,3,4), dtype = int) # (_,3,4)>> _ refers to 3rd Dimension

In [36]:
arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [37]:
arr.size

36

In [38]:
#4D array
arr = np.zeros((3,3,3,4), dtype = int)

In [39]:
arr

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]])

In [40]:
arr.ndim

4

In [41]:
arr = np.zeros((3,3,3,3,4), dtype = int)

In [42]:
arr

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]],



       [[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
    

In [43]:
arr.ndim

5

In [44]:
arr.size

324

In [45]:
arr.shape

(3, 3, 3, 3, 4)

In [48]:
arr = np.zeros((3,4), dtype= int)

In [49]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
arr + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [53]:
a = arr+5

In [54]:
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [60]:
b = a * 2
b

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [61]:
b - 8

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [64]:
np.eye((3) , dtype = int )# generates 3*3 matrix with all diagonal elements as 1 and rest with 0

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [65]:
np.eye(4 , dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [73]:
np.empty((3, 4), dtype = int) # return a new array of given shape and type , without initializing entries , any random values

array([[      2292920691624,                  64,                   0,
                          0],
       [8751735922824839168, 7161908003341623605, 3991987212741862499,
        3775764918343066933],
       [7305174175183823670, 3847592722889585510, 3702580359145535538,
        7305460035305890611]])

In [72]:
np.empty((5,6))

array([[1.13283746e-311, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000, 7.56587583e-307, 5.02034658e+175],
       [1.68743985e+160, 1.28942842e+165, 5.98927918e+174,
        1.63205399e+185, 6.81479592e-067, 5.83384027e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 1.68743985e+160, 1.28942842e+165,
        5.98927918e+174, 1.63205399e+185, 1.04917867e-153],
       [1.94918966e-153, 1.48339952e-076, 2.73418275e-052,
        3.31108018e-033, 2.59027896e-144, 7.79952704e-143]])

In [80]:
#optional >> random module 
#>> gives random value
import random
random.choice((1,2,3,4,5))

5

In [81]:
random.choice("Abhi")

'i'

In [82]:
random.randrange(1,10)

3

In [84]:
random.random() # a random generated b/w 0  and 1

0.8783140097351737

In [91]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [92]:
random.shuffle(lis)

In [93]:
lis

[5, 3, 2, 4, 1]

In [95]:
random.uniform(7,14)

8.8283736734815

In [96]:
#random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [97]:
np.random.random_sample()

0.2510410531035113

In [100]:
np.random.random_sample((5,)) #1 dimesion array of 5 random numbers

array([0.21969978, 0.78242047, 0.41367764, 0.32722341, 0.59844879])

In [101]:
np.random.rand(1)

array([0.01655663])

In [102]:
np.random.rand(2,3)

array([[0.35767477, 0.27512212, 0.92464583],
       [0.06026564, 0.34978477, 0.02207425]])

In [103]:
np.random.randn(2,3) #return a sample from the "standard normal" distribution.

array([[ 1.36266394, -1.06899897, -1.11310551],
       [-0.37060912, -1.01399509,  0.09760165]])

In [104]:
np.random.randint(1,5)

1

In [106]:
arr = np.random.randint(1,5, size = (3,4)) #start from 1 end at 5-1 and give array

In [107]:
arr.ndim

2

In [108]:
arr.shape

(3, 4)

In [109]:
arr.size

12

In [110]:
arr

array([[2, 1, 2, 4],
       [3, 2, 1, 1],
       [2, 2, 4, 1]], dtype=int32)

In [111]:
#reshaping of array
arr.reshape(2,6)

array([[2, 1, 2, 4, 3, 2],
       [1, 1, 2, 2, 4, 1]], dtype=int32)

In [119]:
arr1 = arr.reshape(4,3)

In [120]:
#Note - when you try to reshape it should be a multiple of elements present in an array otherwise it gives error

In [121]:
arr.shape

(3, 4)

In [122]:
arr1.shape

(4, 3)

In [123]:
arr1

array([[2, 1, 2],
       [4, 3, 2],
       [1, 1, 2],
       [2, 4, 1]], dtype=int32)

In [124]:
arr.reshape(12,1)

array([[2],
       [1],
       [2],
       [4],
       [3],
       [2],
       [1],
       [1],
       [2],
       [2],
       [4],
       [1]], dtype=int32)

In [126]:
arr.reshape(4,-1) # Case when you dont know in reshape what should be the row or column just use -1 or any negative values for rows or columns

array([[2, 1, 2],
       [4, 3, 2],
       [1, 1, 2],
       [2, 4, 1]], dtype=int32)

In [127]:
arr.reshape(4,-2)

array([[2, 1, 2],
       [4, 3, 2],
       [1, 1, 2],
       [2, 4, 1]], dtype=int32)

In [129]:
arr.reshape(-1,4)

array([[2, 1, 2, 4],
       [3, 2, 1, 1],
       [2, 2, 4, 1]], dtype=int32)

In [131]:
arr.reshape(12,1).base # to see the original array

array([[2, 1, 2, 4],
       [3, 2, 1, 1],
       [2, 2, 4, 1]], dtype=int32)

In [132]:
arr

array([[2, 1, 2, 4],
       [3, 2, 1, 1],
       [2, 2, 4, 1]], dtype=int32)

In [134]:
arr.reshape(2,2,3) # mulitplication should be equal to arr size

array([[[2, 1, 2],
        [4, 3, 2]],

       [[1, 1, 2],
        [2, 4, 1]]], dtype=int32)

In [136]:
arr.reshape(1,2,2,3)

array([[[[2, 1, 2],
         [4, 3, 2]],

        [[1, 1, 2],
         [2, 4, 1]]]], dtype=int32)

In [137]:
arr.reshape(1,2,2,3).ndim

4

In [139]:
arr.reshape(4,3,1) #3 rows 1 colums repeated 4 times in the 3rd Dimension

array([[[2],
        [1],
        [2]],

       [[4],
        [3],
        [2]],

       [[1],
        [1],
        [2]],

       [[2],
        [4],
        [1]]], dtype=int32)

In [140]:
#conditions on array
arr1 = np.random.randint(1,10,(5,6))

In [141]:
arr1

array([[2, 1, 3, 2, 2, 7],
       [8, 3, 6, 9, 3, 4],
       [8, 3, 2, 4, 5, 6],
       [3, 2, 9, 2, 4, 6],
       [4, 1, 1, 2, 3, 4]], dtype=int32)

In [142]:
arr1.shape

(5, 6)

In [143]:
arr1.size

30

In [144]:
arr1.ndim

2

In [145]:
arr1 

array([[2, 1, 3, 2, 2, 7],
       [8, 3, 6, 9, 3, 4],
       [8, 3, 2, 4, 5, 6],
       [3, 2, 9, 2, 4, 6],
       [4, 1, 1, 2, 3, 4]], dtype=int32)

In [147]:
arr1 > 7

array([[False, False, False, False, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [148]:
arr1[arr1 > 7]# select all elements of arr1 here condition is true

array([8, 9, 8, 9], dtype=int32)

In [149]:
arr1[arr1<3]

array([2, 1, 2, 2, 2, 2, 2, 1, 1, 2], dtype=int32)

In [150]:
arr1

array([[2, 1, 3, 2, 2, 7],
       [8, 3, 6, 9, 3, 4],
       [8, 3, 2, 4, 5, 6],
       [3, 2, 9, 2, 4, 6],
       [4, 1, 1, 2, 3, 4]], dtype=int32)

In [152]:
#to access elements in an array

In [156]:
arr1[0] # arr[__] indexes

array([2, 1, 3, 2, 2, 7], dtype=int32)

In [157]:
arr1[1]

array([8, 3, 6, 9, 3, 4], dtype=int32)

In [159]:
arr1[1][2]

np.int32(6)

In [160]:
arr1

array([[2, 1, 3, 2, 2, 7],
       [8, 3, 6, 9, 3, 4],
       [8, 3, 2, 4, 5, 6],
       [3, 2, 9, 2, 4, 6],
       [4, 1, 1, 2, 3, 4]], dtype=int32)

In [163]:
arr1[3][1]

np.int32(2)

In [167]:
# from 0th row to 2nd row >> we use slicing

In [168]:
arr1[0:3]

array([[2, 1, 3, 2, 2, 7],
       [8, 3, 6, 9, 3, 4],
       [8, 3, 2, 4, 5, 6]], dtype=int32)

In [175]:
# from 0 to 2nd row and 0th and 2nd column
arr1[0:3,[0,2]]

array([[2, 3],
       [8, 6],
       [8, 2]], dtype=int32)

In [176]:
#slicing on both rows and columns together
arr1

array([[2, 1, 3, 2, 2, 7],
       [8, 3, 6, 9, 3, 4],
       [8, 3, 2, 4, 5, 6],
       [3, 2, 9, 2, 4, 6],
       [4, 1, 1, 2, 3, 4]], dtype=int32)

In [177]:
arr1[0:3,[1,2,3]]

array([[1, 3, 2],
       [3, 6, 9],
       [3, 2, 4]], dtype=int32)

In [178]:
arr1[0:3,[0,1]]

array([[2, 1],
       [8, 3],
       [8, 3]], dtype=int32)

In [180]:
arr1[0,[1,3]]

array([1, 2], dtype=int32)

In [181]:
arr1[2:4, [0,3]]

array([[8, 4],
       [3, 2]], dtype=int32)

In [182]:
arr1[2:5]

array([[8, 3, 2, 4, 5, 6],
       [3, 2, 9, 2, 4, 6],
       [4, 1, 1, 2, 3, 4]], dtype=int32)

In [183]:
arr1[2:5, 0:2]

array([[8, 3],
       [3, 2],
       [4, 1]], dtype=int32)

In [185]:
#mathematical operations on 2 array
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [186]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 2]], dtype=int32)

In [187]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 2]], dtype=int32)

In [189]:
arr1 + arr2 # index wise element addition

array([[2, 3, 3],
       [2, 3, 3],
       [4, 2, 4]], dtype=int32)

In [190]:
arr1  - arr2

array([[ 0,  1,  1],
       [ 0, -1, -1],
       [ 0,  0,  0]], dtype=int32)

In [192]:
arr1 * arr2 # index wise multiplication

array([[1, 2, 2],
       [1, 2, 2],
       [4, 1, 4]], dtype=int32)

In [193]:
arr1,arr2

(array([[1, 2, 2],
        [1, 1, 1],
        [2, 1, 2]], dtype=int32),
 array([[1, 1, 1],
        [1, 2, 2],
        [2, 1, 2]], dtype=int32))

In [194]:
arr1 / arr2 # index wise division

array([[1. , 2. , 2. ],
       [1. , 0.5, 0.5],
       [1. , 1. , 1. ]])

In [195]:
4/0 # python gives >> ZeroDivisionError: division by zero

ZeroDivisionError: division by zero

In [197]:
arr1/0 # gives infinity

C:\Users\kumar\AppData\Local\Temp\ipykernel_22496\784161104.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # gives infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [198]:
#matrix multiplication >> matrix is a specialised 2D array
#matrix multiplication is different from index wise multilication

In [200]:
arr1 @ arr2 # way to do matrix multiplication

array([[7, 7, 9],
       [4, 4, 5],
       [7, 6, 8]], dtype=int32)

In [201]:
arr1 * arr2 # it is index wise multiplication

array([[1, 2, 2],
       [1, 2, 2],
       [4, 1, 4]], dtype=int32)

In [202]:
np.dot(arr1,arr2) # another way of matrix multiplication

array([[7, 7, 9],
       [4, 4, 5],
       [7, 6, 8]], dtype=int32)

In [205]:
#Broad casting
arr = np.zeros((3,4),dtype = int)

In [206]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [207]:
arr + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [208]:
a = np.array([1,2,3,4])

In [209]:
arr + a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [210]:
#Transpose matrix >> converting rows to columns and columns to rows
a.T

array([1, 2, 3, 4])

In [ ]:
A = np.array([[1,2,3,4]])